DRIVE_URL = "https://docs.google.com/spreadsheets/d/1TA3wx1zL_YcyIOJ-MjFu18UOUJGIs5cve2YlTUs7p38/export?format=csv&gid=1713652807#gid=1713652807"

password = "hub_sebrae_2026"

[contrata_mais]
url_mensagens = "https://docs.google.com/spreadsheets/d/16iCJzgyIJuTJ2vU4kTAkd77QBWHXUF5LIwF0ao9BSCo/export?format=csv&gid=1472893033#gid=1472893033"
url_cadastros = "https://docs.google.com/spreadsheets/d/16iCJzgyIJuTJ2vU4kTAkd77QBWHXUF5LIwF0ao9BSCo/export?format=csv&gid=1201681050#gid=1201681050"